server:
  port: 8087

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*.xml    #配置mybatis扫描mapper文件xml的路径

wechat:
  url:
  wxUrl:
  baseUrl:
  baseUserKey:
  appId:
  secret:

  oauth2AuthorizeUrl:
  oauth2AccessTokenUrl:

debug:
  verifyCode: 3721

sms:
  apikey: 1
  tpl_id: 2
  url: 3

